// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Plynf Authors
/**
 * Parity test: the client-side shaper (src/lib/shaper.ts) must produce
 * byte-identical output AND identical token counts to the real Python
 * policy engine, for every fixture generated by
 * `scripts/gen_shaper_fixtures.py`.
 *
 * Run: npm run test:parity
 */

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { encode } from "gpt-tokenizer/encoding/o200k_base";
import { shape, compactJson, type Json } from "../src/lib/shaper";

interface Fixture {
  name: string;
  raw: Json;
  keepList: string[];
  expectedShaped: Json;
  expectedRawTokens: number;
  expectedShapedTokens: number;
}

const here = dirname(fileURLToPath(import.meta.url));
const { cases } = JSON.parse(
  readFileSync(join(here, "fixtures", "shaper-parity.json"), "utf-8"),
) as { cases: Fixture[] };

assert.ok(cases.length >= 10, "fixtures look incomplete — regenerate them");

const countTokens = (v: Json) => encode(compactJson(v)).length;

for (const c of cases) {
  test(`shape parity · ${c.name}`, () => {
    const result = shape(c.raw, { keepList: c.keepList });
    assert.deepEqual(
      result.shaped,
      c.expectedShaped,
      `shaped output diverges from the Python engine for ${c.name}`,
    );
  });

  test(`token parity · ${c.name}`, () => {
    assert.equal(
      countTokens(c.raw),
      c.expectedRawTokens,
      `raw token count diverges (serialisation mismatch?) for ${c.name}`,
    );
    assert.equal(
      countTokens(shape(c.raw, { keepList: c.keepList }).shaped),
      c.expectedShapedTokens,
      `shaped token count diverges for ${c.name}`,
    );
  });
}
