// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Plynf Authors
/**
 * Client-side port of the proxy's shaping mechanism — the lossless layer
 * (strip_metadata + drop_empty) and the allow-list projection with its
 * safe fallback. Used by the public savings preview: everything runs in
 * the visitor's browser, nothing is uploaded.
 *
 * ⚠️ PARITY CONTRACT: this module mirrors
 * `services/proxy/src/plinth_proxy/policy_engine.py`. Any behavioural
 * change there must land here too. Enforced by `npm run test:parity`
 * against fixtures generated by `scripts/gen_shaper_fixtures.py` from the
 * real Python engine.
 *
 * Deliberately NOT ported (server-side concerns, not needed for preview):
 * deny_fields, redact_pii, max_response_tokens, block_write_actions.
 */

export type Json =
  | null
  | boolean
  | number
  | string
  | Json[]
  | { [key: string]: Json };

/** Canonicalise a field name: lowercase, strip non-alphanumerics.
 *  order_id == orderId == OrderID == order-id == ORDER_ID. */
export function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

// Mirrors _DEFAULT_METADATA_FIELDS in policy_engine.py (normalised form).
const DEFAULT_METADATA_FIELDS = [
  "created_at",
  "createdAt",
  "CreatedDate",
  "created_by",
  "createdBy",
  "updated_at",
  "updatedAt",
  "LastModifiedDate",
  "modified_at",
  "modifiedAt",
  "modified_by",
  "modifiedBy",
  "SystemModstamp",
  "LastViewedDate",
  "LastReferencedDate",
  "etag",
  "_version",
  "version",
  "rev",
  "_rev",
  "attributes",
];
const METADATA_NORM = new Set(DEFAULT_METADATA_FIELDS.map(norm));

const isObj = (v: Json): v is { [key: string]: Json } =>
  typeof v === "object" && v !== null && !Array.isArray(v);

/** strip_metadata: drop common audit columns, casing/separator-robust. */
export function stripMetadata(value: Json): Json {
  if (isObj(value)) {
    const out: { [key: string]: Json } = {};
    for (const [k, v] of Object.entries(value)) {
      if (!METADATA_NORM.has(norm(k))) out[k] = stripMetadata(v);
    }
    return out;
  }
  if (Array.isArray(value)) return value.map(stripMetadata);
  return value;
}

/** drop_empty: lossless minimisation — remove null / "" / [] / {} fields.
 *  Keeps 0 / 0.0 / false. List length is preserved (elements recursed,
 *  never removed). */
export function dropEmpty(value: Json): Json {
  if (isObj(value)) {
    const out: { [key: string]: Json } = {};
    for (const [k, v] of Object.entries(value)) {
      const vv = dropEmpty(v);
      if (
        vv === null ||
        vv === "" ||
        (Array.isArray(vv) && vv.length === 0) ||
        (isObj(vv) && Object.keys(vv).length === 0)
      ) {
        continue;
      }
      out[k] = vv;
    }
    return out;
  }
  if (Array.isArray(value)) return value.map(dropEmpty);
  return value;
}

/** True if a value carries no usable content (mirrors _looks_empty). */
export function looksEmpty(value: Json): boolean {
  if (isObj(value)) return Object.keys(value).length === 0;
  if (Array.isArray(value)) return value.every(looksEmpty);
  return value === null;
}

const splitPath = (path: string): string[] => path.split(".");

const isPrefix = (fieldPath: string[], allowPath: string[]): boolean => {
  if (allowPath.length > fieldPath.length) return false;
  return allowPath.every((seg, i) => fieldPath[i] === seg);
};

/** Whitelist projection with dotted paths, "a|b|c" synonyms, and
 *  casing/separator-robust matching (mirrors _project_fields). */
export function projectFields(value: Json, allow: string[]): Json {
  if (!isObj(value)) {
    if (Array.isArray(value)) return value.map((item) => projectFields(item, allow));
    return value;
  }
  const allowPaths: string[][] = [];
  for (const a of allow) {
    for (const alt of a.split("|")) {
      const t = alt.trim();
      if (t) allowPaths.push(splitPath(t).map(norm));
    }
  }
  return projectDict(value, allowPaths, []);
}

function projectDict(
  d: { [key: string]: Json },
  allowPaths: string[][],
  currentPath: string[],
): { [key: string]: Json } {
  const out: { [key: string]: Json } = {};
  for (const [key, val] of Object.entries(d)) {
    const newPath = [...currentPath, norm(key)];
    // Mirrors policy_engine._project_dict EXACTLY. isPrefix(fieldPath,
    // allowPath) → allowPath is a prefix of fieldPath (Python arg order).
    const exactMatch = allowPaths.some(
      (ap) => ap.length === newPath.length && isPrefix(newPath, ap),
    );
    // "Allow path is deeper than this key" → newPath is a prefix of ap.
    const nestedMatch = allowPaths.some((ap) => isPrefix(ap, newPath));
    // Descend while the parent of an allow path is a prefix of newPath.
    const descendsInto = allowPaths.some(
      (ap) => ap.length > 1 && isPrefix(newPath, ap.slice(0, -1)),
    );

    if (exactMatch) {
      out[key] = val;
    } else if (descendsInto && isObj(val)) {
      const sub = projectDict(val, allowPaths, newPath);
      if (Object.keys(sub).length > 0) out[key] = sub;
    } else if (descendsInto && Array.isArray(val)) {
      let subList = val.map((item) =>
        isObj(item) ? projectDict(item, allowPaths, newPath) : item,
      );
      subList = subList.filter((s) => !(isObj(s) && Object.keys(s).length === 0));
      if (subList.length > 0) out[key] = subList;
    } else if (nestedMatch) {
      out[key] = val;
    }
  }
  return out;
}

export interface ShapeOptions {
  /** Keep-list (allow_fields). Empty/undefined → lossless layer only. */
  keepList?: string[];
  stripMetadata?: boolean; // default true
  dropEmpty?: boolean; // default true
}

export interface ShapeResult {
  shaped: Json;
  /** True if the keep-list matched nothing and the safe fallback kicked in. */
  fallback: boolean;
  /** Field paths removed from the raw response (e.g. "lineItems[].taxCode"). */
  droppedPaths: string[];
}

/** The preview pipeline — mirrors the relevant subset and ORDER of
 *  policy_engine.apply(): strip_metadata → allow_fields (safe fallback)
 *  → drop_empty. */
export function shape(raw: Json, opts: ShapeOptions = {}): ShapeResult {
  const doStrip = opts.stripMetadata !== false;
  const doDrop = opts.dropEmpty !== false;
  const keep = (opts.keepList ?? []).filter((k) => k.trim() !== "");

  let out: Json = raw;
  let fallback = false;

  if (doStrip) out = stripMetadata(out);

  if (keep.length > 0) {
    const projected = projectFields(out, keep);
    if (looksEmpty(projected) && !looksEmpty(out)) {
      fallback = true; // schema mismatch → never blank the response
    } else {
      out = projected;
    }
  }

  if (doDrop) out = dropEmpty(out);

  return { shaped: out, fallback, droppedPaths: diffPaths(raw, out) };
}

/** Collect field paths present in `raw` but absent in `shaped`. */
export function diffPaths(raw: Json, shaped: Json, prefix = ""): string[] {
  const dropped: string[] = [];
  if (isObj(raw)) {
    const shapedObj = isObj(shaped) ? shaped : {};
    for (const [k, v] of Object.entries(raw)) {
      const path = prefix ? `${prefix}.${k}` : k;
      if (!(k in shapedObj)) {
        dropped.push(path);
      } else {
        dropped.push(...diffPaths(v, shapedObj[k], path));
      }
    }
  } else if (Array.isArray(raw) && Array.isArray(shaped)) {
    // Element-wise (lists keep their length in the lossless layer; the
    // projection filters empty dicts, so guard against index drift).
    const n = Math.min(raw.length, shaped.length);
    for (let i = 0; i < n; i++) {
      dropped.push(...diffPaths(raw[i], shaped[i], `${prefix}[]`));
    }
  }
  return [...new Set(dropped)];
}

/** Compact JSON, non-ASCII escaped — byte-identical to Python's
 *  `json.dumps(value, separators=(",", ":"))` (ensure_ascii=True),
 *  which is what the proxy counts tokens against. */
export function compactJson(value: Json): string {
  const s = JSON.stringify(value);
  // Escape all non-ASCII as \\uXXXX like Python's ensure_ascii (non-BMP
  // chars become surrogate pairs in both runtimes).
  return s.replace(/[\u0080-\uffff]/g, (ch) => {
    return "\\u" + ch.charCodeAt(0).toString(16).padStart(4, "0");
  });
}
