#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Plynf one-command installer.
#
# Brings up a self-hosted Plynf stack (proxy + dashboard, mock-mode)
# in ~60 seconds via Docker Compose. Idempotent — re-running is safe.
#
# Usage:
#   curl -fsSL https://plynf.com/install.sh | sh
#   # or with options:
#   curl -fsSL https://plynf.com/install.sh | sh -s -- --port 7430 --dir ~/.plynf

set -euo pipefail

readonly PLYNF_VERSION="${PLYNF_VERSION:-latest}"
INSTALL_DIR="${PLYNF_INSTALL_DIR:-$HOME/.plynf}"
PROXY_PORT="${PLYNF_PROXY_PORT:-7430}"
DASHBOARD_PORT="${PLYNF_DASHBOARD_PORT:-7424}"
SKIP_OPEN="${PLYNF_SKIP_OPEN:-0}"

while [ $# -gt 0 ]; do
  case "$1" in
    --dir)        INSTALL_DIR="$2"; shift 2;;
    --port)       PROXY_PORT="$2"; shift 2;;
    --dashboard)  DASHBOARD_PORT="$2"; shift 2;;
    --no-open)    SKIP_OPEN=1; shift;;
    --version)    echo "Plynf installer · ${PLYNF_VERSION}"; exit 0;;
    --help|-h)
      cat <<EOF
Plynf installer

Options:
  --dir DIR         Install location (default: \$HOME/.plynf)
  --port PORT       Proxy port (default: 7430)
  --dashboard PORT  Dashboard port (default: 7424)
  --no-open         Don't auto-open the dashboard in a browser
  --version         Print version and exit

Environment overrides:
  PLYNF_VERSION, PLYNF_INSTALL_DIR, PLYNF_PROXY_PORT,
  PLYNF_DASHBOARD_PORT, PLYNF_SKIP_OPEN
EOF
      exit 0;;
    *) echo "Unknown option: $1" >&2; exit 1;;
  esac
done

# ── colours ──────────────────────────────────────────────────────────
if [ -t 1 ]; then
  C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'; C_RED=$'\033[31m'
  C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_RESET=$'\033[0m'
else
  C_BOLD=""; C_DIM=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_RESET=""
fi

say()  { printf "%s\n" "${C_BOLD}▸ $*${C_RESET}"; }
done_() { printf "%s\n" "${C_GREEN}✓ $*${C_RESET}"; }
warn() { printf "%s\n" "${C_YELLOW}⚠ $*${C_RESET}"; }
die()  { printf "%s\n" "${C_RED}✗ $*${C_RESET}" >&2; exit 1; }

# ── preflight ────────────────────────────────────────────────────────
say "Plynf installer"
printf "  ${C_DIM}install dir:${C_RESET}    %s\n" "$INSTALL_DIR"
printf "  ${C_DIM}proxy port:${C_RESET}     %s\n" "$PROXY_PORT"
printf "  ${C_DIM}dashboard port:${C_RESET} %s\n" "$DASHBOARD_PORT"
echo

command -v docker >/dev/null 2>&1 \
  || die "Docker not found. Install Docker Desktop: https://docker.com/products/docker-desktop"

# Detect compose plugin vs standalone binary.
COMPOSE=""
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "Docker Compose not found. Modern Docker Desktop bundles it; on Linux: https://docs.docker.com/compose/install/"
fi

docker info >/dev/null 2>&1 \
  || die "Docker daemon not reachable. Start Docker Desktop, then re-run."

# Check port availability — emit clear errors before compose hits it.
check_port() {
  local p="$1"
  if (echo > /dev/tcp/127.0.0.1/"$p") >/dev/null 2>&1; then
    die "Port $p is already in use. Pass --port <other-port> to install.sh."
  fi
}
check_port "$PROXY_PORT"
check_port "$DASHBOARD_PORT"

# ── prepare install dir ───────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"/{data,policies,logs}

# ── compose file ──────────────────────────────────────────────────────
cat > "$INSTALL_DIR/docker-compose.yml" <<EOF
# Auto-generated by install-plynf.sh — safe to edit, will not be overwritten.
services:
  proxy:
    image: ghcr.io/nico-schindlbeck-jpg/plynf-proxy:${PLYNF_VERSION}
    container_name: plynf-proxy
    restart: unless-stopped
    ports:
      - "${PROXY_PORT}:7430"
    environment:
      PLINTH_PROXY_DEMO_MODE: "true"
      PLINTH_PROXY_POLICY_OVERRIDES_PATH: "/data/policy-overrides.json"
      PLINTH_PROXY_SAVINGS_LOG: "/data/savings.jsonl"
    volumes:
      - ${INSTALL_DIR}/data:/data
      - ${INSTALL_DIR}/policies:/etc/plynf/policies:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7430/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  dashboard:
    image: ghcr.io/nico-schindlbeck-jpg/plynf-dashboard:${PLYNF_VERSION}
    container_name: plynf-dashboard
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT}:7424"
    environment:
      PLINTH_PROXY_URL: "http://proxy:7430"
    depends_on:
      proxy:
        condition: service_healthy

networks:
  default:
    name: plynf
EOF

done_ "Generated $INSTALL_DIR/docker-compose.yml"

# ── pull + start ──────────────────────────────────────────────────────
say "Pulling images (first run downloads ~250 MB, ~60 s on decent wifi)…"
( cd "$INSTALL_DIR" && $COMPOSE pull --quiet )

say "Starting Plynf…"
( cd "$INSTALL_DIR" && $COMPOSE up -d )

# ── wait for proxy health ─────────────────────────────────────────────
say "Waiting for proxy to become healthy…"
deadline=$(( $(date +%s) + 60 ))
while [ "$(date +%s)" -lt "$deadline" ]; do
  if curl -sf "http://127.0.0.1:${PROXY_PORT}/healthz" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

if ! curl -sf "http://127.0.0.1:${PROXY_PORT}/healthz" >/dev/null 2>&1; then
  warn "Proxy didn't report healthy within 60 s — check logs:"
  echo   "      cd $INSTALL_DIR && $COMPOSE logs --tail=80"
  exit 1
fi

# ── success summary ───────────────────────────────────────────────────
done_ "Plynf is up."
echo
printf "  ${C_BOLD}Proxy${C_RESET}      http://localhost:${PROXY_PORT}\n"
printf "  ${C_BOLD}Dashboard${C_RESET}  http://localhost:${DASHBOARD_PORT}\n"
echo
printf "  ${C_DIM}Try it:${C_RESET}\n"
printf "    curl http://localhost:${PROXY_PORT}/healthz\n"
printf "    curl -X POST http://localhost:${PROXY_PORT}/v1/tools/get_order/invoke \\\\\n"
printf "         -H \"Content-Type: application/json\" \\\\\n"
printf "         -d '{\"arguments\":{\"order_id\":\"12345\"}}' | jq\n"
echo
printf "  ${C_DIM}Stop / start / logs:${C_RESET}\n"
printf "    cd $INSTALL_DIR && $COMPOSE down    # stop\n"
printf "    cd $INSTALL_DIR && $COMPOSE up -d   # start\n"
printf "    cd $INSTALL_DIR && $COMPOSE logs -f # logs\n"
echo

# ── open dashboard ────────────────────────────────────────────────────
if [ "$SKIP_OPEN" = "0" ]; then
  if command -v open >/dev/null 2>&1; then
    open "http://localhost:${DASHBOARD_PORT}" >/dev/null 2>&1 || true
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "http://localhost:${DASHBOARD_PORT}" >/dev/null 2>&1 || true
  fi
fi
