#!/usr/bin/env bash
# pin-compose-digests.sh — Replace mutable tags with immutable @sha256: digests.
#
# Usage:
#   scripts/pin-compose-digests.sh deploy/compose.prod.yml v1.7
#
# Result:
#   deploy/compose.prod.pinned.yml  (next to the input)
#   Every  image: ghcr.io/org/svc:v1.7  →  image: ghcr.io/org/svc@sha256:...
#
# Why pin? :v1.7 is just a label that can be overwritten by a force-push to
# GHCR. @sha256:... is content-addressable — the bytes the digest refers to
# never change. For production deploys, supply-chain-conscious customers
# want digests, not tags.
#
# Requirements: docker, jq.

set -euo pipefail

usage() {
    cat <<EOF >&2
Usage: $(basename "$0") <compose-file> <version>

  compose-file  Path to a compose YAML referencing ghcr.io/.../...:<version>
  version       The mutable tag to resolve (e.g. v1.7, latest, sha-abcd123)

Produces <compose-file%.yml>.pinned.yml next to the input.

Example:
  $(basename "$0") deploy/compose.prod.yml v1.7
  → writes deploy/compose.prod.pinned.yml
EOF
    exit 1
}

[ $# -eq 2 ] || usage
INPUT="$1"
VERSION="$2"
[ -f "$INPUT" ] || { echo "✘ not found: $INPUT" >&2; exit 1; }

OUTPUT="${INPUT%.yml}.pinned.yml"

command -v docker >/dev/null || { echo "✘ docker not found in PATH" >&2; exit 2; }
command -v jq     >/dev/null || { echo "✘ jq not found in PATH" >&2; exit 2; }

echo "→ Resolving digests for tag :${VERSION}"

# Find all unique ghcr.io references with this version tag
mapfile -t images < <(
    grep -oE 'ghcr\.io/[^[:space:]"]+:'"$(printf '%s' "$VERSION" | sed 's/[.[\^$*]/\\&/g')" "$INPUT" \
    | sort -u
)

if [ "${#images[@]}" -eq 0 ]; then
    echo "✘ no images matching :${VERSION} found in ${INPUT}" >&2
    exit 3
fi

echo "  Found ${#images[@]} unique image references"

# Build a sed expression file (so we run sed once, not N times)
SED_FILE="$(mktemp)"
trap 'rm -f "$SED_FILE"' EXIT

failed=0
for img in "${images[@]}"; do
    # img is like "ghcr.io/org/plynf-workspace:v1.7"
    repo="${img%:*}"
    echo -n "  ${img} ... "
    if digest=$(docker buildx imagetools inspect "$img" --format '{{json .Manifest}}' 2>/dev/null | jq -r '.digest' 2>/dev/null); then
        if [ -n "$digest" ] && [ "$digest" != "null" ]; then
            echo "${digest}"
            # Escape forward slashes for sed
            escaped_img=$(printf '%s' "$img" | sed 's|/|\\/|g')
            escaped_pinned=$(printf '%s@%s' "$repo" "$digest" | sed 's|/|\\/|g')
            printf 's/%s/%s/g\n' "$escaped_img" "$escaped_pinned" >> "$SED_FILE"
        else
            echo "✘ no digest"
            failed=$((failed + 1))
        fi
    else
        echo "✘ inspect failed"
        failed=$((failed + 1))
    fi
done

if [ "$failed" -gt 0 ]; then
    echo "✘ ${failed} image(s) failed digest resolution. Aborting." >&2
    exit 4
fi

sed -f "$SED_FILE" "$INPUT" > "$OUTPUT"

# Header injection — make it obvious this file is generated
{
    head -1 "$OUTPUT"
    cat <<EOF
#
# ⚠ AUTO-GENERATED by scripts/pin-compose-digests.sh
# Source:    ${INPUT}
# Pinned at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Version:   ${VERSION}
# Do not edit by hand — regenerate to update digests.
#
EOF
    tail -n +2 "$OUTPUT"
} > "${OUTPUT}.tmp" && mv "${OUTPUT}.tmp" "$OUTPUT"

echo ""
echo "✓ Wrote pinned compose to ${OUTPUT}"
echo "  Use with: docker compose -f ${OUTPUT} up -d --wait"
